version: '3.8'

services:
  drew-dashboard:
    build: .
    container_name: drew-dashboard
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drew.rule=Host(`apps.syncronhub.com`) && PathPrefix(`/drew`)"
      - "traefik.http.services.drew.loadbalancer.server.port=5000"

  # Optional: Add Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: drew-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - drew-dashboard
    restart: unless-stopped